config/routes.rb
Rails.application.routes.draw do
  get 'cv/index'

  

  match '/dashboard.json' => 'file#create', via: :post
  match '/todo.json' => 'file#todo', via: :post
  match '/cv/personalia.json' => 'cv#personalia', via: :post
  match '/cv/talen.json' => 'cv#talen', via: :post
  match '/cv/opleidingen.json' => 'cv#opleidingen', via: :post
  match '/cv/werkervaring.json' => 'cv#werkervaring', via: :post

  

  get '/:locale' => 'shas#index'

  scope "/:locale" do
    root 'shas#index'
    resources :shas
    match '/storagedb', to: 'shas#storage', via: 'get'
    match '/public_download', to: 'shas#public', via: 'get'
    match '/storagedb', to: 'shas#storage', via: 'get'
    match '/help', to: 'shas#help', via: 'get'
    match '/settings', to: 'shas#settings', via: 'get'
    match '/status', to: 'shas#status', via: 'get'
    match '/change', to: 'shas#change', via: 'get'
    match '/test', to: 'shas#test', via: 'get'
  end

end

app/models/blob.rb
class Blob < ActiveRecord::Base
end

app/controllers/blobs_controller.rb
class BlobsController < ApplicationController

	def create		
		file_params = params[:blob][:file_input]

		camli = Camli.new(file_params)

		redirect_to :back
	end

	def index

		c = Camli.new()

		@blob = Blob.new
		c.make_lists()
		last_uploads = c.get_last_n_uploads(5)
		@filenames = last_uploads[0]
		@icons = last_uploads[1]

	end

	def storage

		filter = params[:t]

		@blob = Blob.new

		c = Camli.new()

		
		#Used to create the values for the filter sub-menu
		#@filetypes = c.get_filetypes_for_filter()

		#@extensions = c.get_extensions_for_filter(@filetypes)

		@data = c.show_everything(filter)

		#Gets the ip for the thumbnails
		@ip = Socket.ip_address_list.find { |ai| ai.ipv4? && !ai.ipv4_loopback? }.ip_address

		if !@data.nil?
			@filenames = @data[0].reverse
			@icons = @data[1].reverse
			@thumbnails = @data[2].reverse
			@links = @data[3].reverse
			@keys = @data[4].reverse
		end

		last_uploads = c.get_last_n_uploads(5)
		@filenames_n = last_uploads[0]
		@icons_n = last_uploads[1]

	end

	def show
		
	end

	def public

		key = params[:d]

		c = Camli.new('')

		search_result = c.download(key,'public')

		if search_result.nil?
			redirect_to root_path
		else
			sha1 = search_result[0]
			filename = search_result[1]
			
			if !sha1.nil?
				send_data `camget -contents #{sha1}`, :filename => filename
			else
				redirect_to root_path
			end
		end

	end

	def private

		@key = params[:d]

		c = Camli.new('')

		sha = c.get_sha_from_attr_value('download', @key)

		search_result = c.download(@key, 'private')

		if search_result.nil?
			redirect_to root_path
		else
			@filename=c.get_permanode_attributes(sha, 'filename')[0]
		end

	end

	def private_check_and_send

		auth = params[:auth]
		key = params[:key]

		c = Camli.new

		permanode_sha = c.get_sha_from_attr_value('download', key)

		search_result = c.download(key, 'private')

		if search_result.nil?
			redirect_to '/upload'
		else
			sha1 = search_result[0]
			filename = search_result[1]

			logger.debug "sha1, auth = #{sha1}, #{auth}"

			valid = c.check_auth(permanode_sha, auth)

			if valid
				send_data `camget -contents #{sha1}`, :filename => filename
			else
				redirect_to '/upload'
			end
		end
	end

	def about

		@blob = Blob.new
		c = Camli.new

		last_uploads = c.get_last_n_uploads(5)
		@filenames_n = last_uploads[0]
		@icons_n = last_uploads[1]

	end
end

app/helpers/blobs_helper.rb
module BlobsHelper
end

app/views/blobs/about.html.erb
<!DOCTYPE html>
  <head>
      <meta charset="utf-8">
      <title>Memocom.org</title>
      <meta name="description" content="">
      <meta name="author" content="">
      
      <!-- Fonts -->
      <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

  </head>
  <body>
    <div id="wrapper">
        <div id="main_nav_bar">
            <div id="logo">
                <a href=""><img src="assets/logo_temp.png" alt=""/></a>
            </div>
            <div id="nav_main">
                <ul>
                    <li><%= link_to 'Home', root_path %></li>
                    <li><span>|</span></li>
                    <li><%= link_to 'Storage', storage_path %>
                    <li><span>|</span></li>
                    <li class="active"><%= link_to 'About', about_path%></li>
                </ul>
            </div>
             <div id="nav_user">
                <ul>
                    <li class="notification_button" title="Notifications">
                        <a href="#">
                            <img src="assets/Icons/medium/16x20_notification.png" alt="Notifications"/>                     
                        </a>
                        <ul>
                            <li class="notification_title">Notifications:</li>
                            <% @filenames_n.each_with_index do |upload, i| %>
                                <li>
                                    <a href="#">
                                        <%= image_tag @icons_n[i] %>
                                        <span>- <%= upload %> uploaded</span>
                                        <div class="clear"></div>
                                    </a>
                                </li>
                            <% end %>
                        </ul>
                    </li>
                    <li title="Upload">
                        <a href="#upload-popup" class="open-popup-link">
                            <img src="assets/Icons/medium/18x20_upload.png" alt="Upload files"/>
                        </a>
                    </li>
                <!--<li>
                        <a href="#">
                            <img src="assets/Icons/medium/15x20_sync.png" alt="Sync storage"/>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="assets/Icons/medium/18x20_settings.png" alt="Settings"/>
                        </a>
                    </li>
                    <li>
                        <a href="#"><img src="assets/Icons/medium/15x20_logout.png" alt="Logout"/>
                        </a>
                    </li>-->
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div id="main_content">
            <div id="side_nav">
                
            </div>
            <div id="content_wrapper" class="about_page">
                <div id="about_header">
                    <div id="page_title">
                        <h1>About Memocom.org</h1>
                    </div>
                    <h2>Jouw digitale gegevens van jou en van jou alleen!</h2>
                    <p>
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
              </p>
                </div>
                <div class="temp_content">
                    <h2>Lorem ipsum dolor sit amet</h2>
                    <p>
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
              </p>
                    <p>
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
              </p>
                    <h2>Vivamus elementum</h2>
                    <ul>
                        <li>Aenean leo ligula</li>
                        <li>Aenean leo ligula</li>
                        <li>Aenean leo ligula</li>
                        <li>Aenean leo ligula</li>
                    </ul>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div id="footer">
        <div class="inner">
            <span>Memocom.org</span>
        </div>
    </div>
      
    <!-- Pop-ups -->
    <div id="upload-popup" class="white-popup mfp-hide">
        <div id="upload_form_wrapper">
            <div class="upload_form">
                <h1>Upload</h1>
                <%= form_for(@blob) do |f| %>
                    <%= f.file_field :file_input %><br /><br />
                    <%= hidden_field_tag(:return_to, "storage") %>
                    <%= f.submit "Upload" %>
                <% end %>
            </div>
            <div class="loading_status">
                <img src="assets/Icons/loading.gif" alt="Uploading" title="Uploading"/>
            </div>
            <div class="clear"></div>
        </div> 
    </div>

    <div id="share-popup" class="white-popup mfp-hide">
        <div id="share_wrapper">
            <h1>Share</h1>
            <div class="public_share">
                <h2>Public:</h2>
                <div class="link_wrapper">
                    <p>Link: <a href="#" class="share_link">231237y1h2euihe7ye2uhe2uhe</a></p>
                    <a href="#"><img src="assets/Icons/small/20x20_clipboard.png" alt=""/></a>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="private_share">
                <h2>Private:</h2>
                <div class="link_wrapper">
                    <p>Link: <a href="#" class="share_link">231237y1h2euihe7ye2uhe2uhe</a></p>
                    <a href="#"><img src="assets/Icons/small/20x20_clipboard.png" alt=""/></a>
                    <div class="clear"></div>
                    <ul class="passkeys">
                        
                    </ul>
                </div>
            </div>
        </div> 
    </div>
    <!-- End Pop-ups --> 
      
    <script type="text/javascript">
        $(function(){ //DOM Ready
        
            $('.open-popup-link').magnificPopup({
                type:'inline',
                midClick: true
            });
            
        });
    </script>
  </body>
</html>

app/views/blobs/index.html.erb
  <head>
      <meta charset="utf-8">
      <title>Memocom.org</title>
      <meta name="description" content="">
      <meta name="author" content="">
      
      <!-- Fonts -->
      <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
      
  </head>
  <body>
    <div id="wrapper">
        <div id="main_nav_bar">
            <div id="logo">
                <a href=""><img src="assets/logo_temp.png" alt=""/></a>
            </div>
            <div id="nav_main">
                <ul>
                    <li class="active"><%= link_to "Home", blobs_path %></li>
                    <li><span>|</span></li>
                    <li><%= link_to "Storage", storage_path %></li>
                    <li><span>|</span></li>
                    <li><%= link_to 'About', about_path%></li>
                </ul>
            </div>
            <div id="nav_user">
                <ul>
                    <li class="notification_button">
                        <a href="">
                            <img src="assets/Icons/medium/16x20_notification.png" alt="Notifications"/>                     
                        </a>
                        <ul>
                            <li class="notification_title">Notifications:</li>
                            <% @filenames.each_with_index do |upload, i| %>
                                <li>
                                    <a href="#">
                                        <%= image_tag @icons[i] %>
                                        <span>- <%= upload %> uploaded</span>
                                        <div class="clear"></div>
                                    </a>
                                </li>
                            <% end %>
                        </ul>
                    </li>
                    <li>
                        <a href="#upload-popup" class="open-popup-link">
                            <img src="assets/Icons/medium/18x20_upload.png" alt="Upload files"/>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div id="main_content">
            <div id="content_wrapper" class="home">
                <div class="gridster">
                    <ul>
                        <li data-row="1" data-col="1" data-sizex="1" data-sizey="1"></li>
                        <li data-row="2" data-col="1" data-sizex="1" data-sizey="1"></li>
                        <li data-row="3" data-col="1" data-sizex="1" data-sizey="1"></li>
                        <li data-row="4" data-col="1" data-sizex="1" data-sizey="1"></li>

                        <li data-row="1" data-col="2" data-sizex="2" data-sizey="1"></li>
                        <li data-row="2" data-col="2" data-sizex="2" data-sizey="2"></li>
                        <li data-row="3" data-col="2" data-sizex="1" data-sizey="1"></li>
                        <li data-row="4" data-col="2" data-sizex="2" data-sizey="1"></li>

                        <li data-row="1" data-col="4" data-sizex="1" data-sizey="1"></li>
                        <li data-row="2" data-col="4" data-sizex="2" data-sizey="1"></li>
                        <li data-row="3" data-col="4" data-sizex="1" data-sizey="1"></li>

                        <li data-row="1" data-col="5" data-sizex="1" data-sizey="1"></li>
                        <li data-row="3" data-col="5" data-sizex="1" data-sizey="1"></li>

                        <li data-row="1" data-col="6" data-sizex="1" data-sizey="1"></li>
                        <li data-row="2" data-col="6" data-sizex="1" data-sizey="2"></li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="footer">
            <div class="inner">
                <span>Memocom.org</span>
            </div>
        </div>
    </div>
      
    <!-- Pop-up -->
    <div id="upload-popup" class="white-popup mfp-hide">
        <div id="upload_form_wrapper">
            <div class="upload_form">
                <h1>Upload</h1>
                <%= form_for(@blob) do |f| %>
                    <%= f.file_field :file_input %><br /><br />
                    <%= hidden_field_tag(:return_to, "storage") %>
                    <%= f.submit "Upload" %>
                <% end %>
            </div>
            <div class="loading_status">
                <img src="assets/Icons/loading.gif" alt="Uploading" title="Uploading"/>
            </div>
            <div class="clear"></div>
        </div> 
    </div>
    <!-- End Pop-up --> 
      
    <script type="text/javascript">
        $(function(){ //DOM Ready
        
            $('.open-popup-link').magnificPopup({
                type:'inline',
                midClick: true
            });

            if($('.gridster')){
                //Initialize gridster
                $(".gridster ul").gridster({
                    widget_margins: [20, 20],
                    widget_base_dimensions: [140, 140]
                });
            }
            
        });
    </script>
  </body>
</html>

app/views/blobs/new.html.erb
<center>
<h1>Upload File</h1>
<div class="row">
<div class="span6 offset3">
<%= form_for(@blob) do |f| %>
<%= f.file_field :file_input %><br /><br />
<%= f.submit "Upload" %>

<%= image_tag "banaan.jpg" %>
<% end %>
</div>
</div>
</center>

app/views/blobs/private.html.erb
<!DOCTYPE html>
  <head>
      <meta charset="utf-8">
      <title>Memocom.org</title>
      <meta name="description" content="">
      <meta name="author" content="">

      <!-- CSS -->
      <link rel="stylesheet" href="css/style.css">
      <link rel="stylesheet" href="css/lightbox.css"> 
      <link rel="stylesheet" type="text/css" href="css/jquery.gridster.css">
      
      <!-- Fonts -->
      <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
      
      <!-- Javascript -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
      
      <script src="js/jquery.gridster.js" type="text/javascript" charset="utf-8"></script>
      
      <script src="js/lightbox.js"></script> 
      
      <script src="js/script.js"></script>
      
  </head>
  <body>
      <div id="wrapper">
          <div id="main_nav_bar">
            <div id="logo">
                <a href="/blobs"><img src="assets/logo_temp.png" alt=""/></a>
            </div>
          </div>
          <div id="share_header">
              <h1>Welcome to the Memocom of "User"</h1>
              <p>
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
              </p>
              <p>Would you like to join the revolution?<br><a href="#">www.memocom.org</a></p>
              
          </div>
          <div id="share_content">
              <h2>Please enter the password:</h2>
              <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
              <%= form_tag("/private_download", method: "get") do %>
				<%= text_field_tag(:auth)%>
				<%= hidden_field_tag(:key, @key) %><br />
				<%= submit_tag("Submit") %>
			  <% end %>
          </div>
      </div>
  </body>
</html>

app/views/blobs/storage.html.erb
<!DOCTYPE html>
  <head>
      <meta charset="utf-8">
      <title>Memocom.org</title>
      <meta name="description" content="">
      <meta name="author" content="">

      <!-- Fonts -->
      <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

      <!-- Javascript -->

  </head>
  <body>
    <div id="wrapper">
        <div id="main_nav_bar">
            <div id="logo">
                <a href=""><img src="assets/logo_temp.png" alt=""/></a>
            </div>
            <div id="nav_main">
                <ul>
                    <li><%= link_to "Home", blobs_path %></li>
                    <li><span>|</span></li>
                    <li class="active"><%= link_to "Storage", storage_path %>   </li>
                <!--<li><span>|</span></li>
                    <li><a href="#">Mail</a></li>
                    <li><span>|</span></li>
                    <li><a href="#">Social</a></li>
                    <li><span>|</span></li>
                    <li><a href="#">Contacts</a></li>-->
                    <li><span>|</span></li>
                    <li><%= link_to 'About', about_path %></li>
                </ul>
            </div>
             <div id="nav_user">
                <ul>
                    <li class="notification_button">
                        <a href="">
                            <img src="assets/Icons/medium/16x20_notification.png" alt="Notifications"/>                     
                        </a>
                        <ul>
                            <li class="notification_title">Notifications:</li>

                                <% @filenames_n.each_with_index do |upload, i| %>
                                    <li>
                                        <a href="#">
                                            <%= image_tag @icons_n[i] %>
                                            <span>- <%= upload %> uploaded</span>
                                            <div class="clear"></div>
                                        </a>
                                    </li>
                                <% end %>

                                

                        </ul>
                    </li>
                    <li>
                        <a href="#upload-popup" class="open-popup-link">
                            <img src="assets/Icons/medium/18x20_upload.png" alt="Upload files"/>
                        </a>
                    </li>
                <!--<li>
                        <a href="#">
                            <img src="assets/Icons/medium/15x20_sync.png" alt="Sync storage"/>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="assets/Icons/medium/18x20_settings.png" alt="Settings"/>
                        </a>
                    </li>
                    <li>
                        <a href="#"><img src="assets/Icons/medium/15x20_logout.png" alt="Logout"/>
                        </a>
                    </li>-->
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div id="main_content">
            <div id="side_nav">
                <ul>
                    <li>
                        <div class="sidebar_icon">
                            <img src="assets/Icons/small/16x16_filter.png" alt="" />
                        </div>                    
                        <div id="filter_slideout" class="sidebar_slideout">
                            <ul>
                                <li class="filter_title">Filter storage on:</li>
                                
                                
                            <li class="filter_button"><a href="#">Filter</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
            <div id="content_wrapper">
                <div id="page_title">
                    <h1>Storage</h1>
                </div>
                <div id="files_wrapper">
                    
                    <!-- ITEMS -->

                    <% if @data.nil? %>

                    Er zijn geen bestanden gevonden.

                    <% end %>

                    <% if !@filenames.nil? %>

                        <% @filenames.each_with_index do |item, i| %>
                        
                        <div class="item">
                            <div class="thumbnail">
                                <% thumb = @thumbnails[i] %>
                                <% thumb = thumb.sub("IP_HERE_TEMP_HJK", @ip) %>
                                <%= image_tag thumb %>
                            </div>
                            <div class="info_overlay">
                                <div class="title">
                                    <span><%= item %></span>
                                </div>
                                <div class="icon">
                                    <%= image_tag @icons[i] %>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="buttons">
                                <div class="detail_button">
                                    <a href="#details-popup" class="open-popup-link">
                                        <img src="assets/Icons/details.png" alt=""/>
                                    </a>
                                </div>
                                <div class="share_button" onclick="setShareInfo('<%=item%>', 'public?d=<%= @links[i]%>', 'private?d=<%= @links[i]%>', <%= @keys[i] %>);">
                                    <a href="#share-popup" class="open-popup-link">
                                        <img src="assets/Icons/share.png" alt=""/>
                                    </a>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="bg"></div>
                        </div>

                        <% end %>
                    
                    <% end %>

                    <!-- END ITEMS -->
                    
                    <div class="clear"></div>
                </div>
            </div>
            <div id="">
            
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div id="footer">
        <div class="inner">
            <span>Memocom.org</span>
        </div>
    </div>
      
    <!-- Pop-ups -->
    <div id="upload-popup" class="white-popup mfp-hide">
        <div id="upload_form_wrapper">
            <div class="upload_form">
                <h1>Upload</h1>
                <%= form_for(@blob) do |f| %>
                    <%= f.file_field :file_input, multiple: true %><br /><br />
                    <%= hidden_field_tag(:return_to, "storage") %>
                    <%= f.submit "Upload" %>
                <% end %>
            </div>
            <div class="loading_status">
                <img src="assets/Icons/loading.gif" alt="Uploading" title="Uploading"/>
            </div>
            <div class="clear"></div>
        </div> 
    </div>

    <div id="details-popup" class="white-popup mfp-hide">
        <div id="details_wrapper">
            <h1>Details</h1>
            <div class="details_popup_top">
                <div class="detail_image">
                    <img src="assets/Icons/32x32/32x32_audio.png" alt=""/>
                    <div class=""></div>
                </div>
                <div class="detail_info">
                    <div class="detail_title">
                        <h2>Banaan</h2>
                        <img src="assets/Icons/32x32/32x32_audio.png" alt=""/>
                        <div class="clear"></div>
                    </div>
                    <table>
                        <tr>
                            <td>Date:</td>
                            <td>20 - 11 - 14</td>
                        </tr>
                    </table>
                </div>
                <div class="clear"></div>
            </div>
            <div class="details_popup_bottom">
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. </p>
            </div>
        </div> 
    </div>

    <div id="share-popup" class="white-popup mfp-hide">
        <div id="share_wrapper">
            <h1>Share</h1>
            <div class="public_share">
                <h2>Public:</h2>
                <div class="link_wrapper">
                    <p>Link: <a href="#" class="share_link">231237y1h2euihe7ye2uhe2uhe</a></p>
                    <span>Kopieer en plak om de link te delen.</span>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="private_share">
                <h2>Private:</h2>
                <div class="link_wrapper">
                    <p>Link: <a href="#" class="share_link">231237y1h2euihe7ye2uhe2uhe</a></p>
                    <span>Kopieer en plak de link en een wachtwoord om te deze delen.</span>
                    <div class="clear"></div>
                    <ul class="passkeys">
                        <li>Key One</li>
                        <li>Key Two</li>
                        <li>Key Three</li>
                    </ul>
                </div>
            </div>
        </div> 
    </div>




    <!-- End Pop-ups --> 
      
    <script type="text/javascript">
        $(function(){ //DOM Ready
        
            $('.open-popup-link').magnificPopup({
                type:'inline',
                midClick: true
            });
            
        });
    </script>
  </body>
</html>